# Generated by Django 4.1.7 on 2023-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0012_alter_mpesapayment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
