# Generated by Django 4.1.7 on 2023-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_agentnotification_remove_batterystation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='company/trends')),
                ('imgurl', models.CharField(blank=True, max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
