# Generated by Django 4.1.7 on 2023-08-11 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bike_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(default='N/A', max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('id_no', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=100)),
                ('date_registered', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
