# Generated by Django 4.1.7 on 2023-08-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='is_delete',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='riders',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
