# Generated by Django 4.1.7 on 2023-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_riders_is_delete_riders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='alt_mobile',
            field=models.CharField(default='0700****00', max_length=20),
        ),
        migrations.AddField(
            model_name='riders',
            name='mobile',
            field=models.CharField(default='0700****00', max_length=20),
        ),
    ]
